baseurl: https://pythonandr.netlify.app/
languageCode: en-us
title: A Hugo website
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
menu:
  main:
    - name: About
      url: /about/
    - name: R materials
      url: https://rdataviz.netlify.app/
    - name: Python materials
      url: https://pythonviz.netlify.app/
    - name: Case study
      url: https://rdataviz.netlify.app/2023/05/case-study/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo2.jpeg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
